"""empty message

Revision ID: 2ca41b6a7d7b
Revises: 
Create Date: 2021-11-23 19:41:18.007795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca41b6a7d7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('stu_card', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stu_name', sa.String(length=15), nullable=False),
    sa.Column('college', sa.String(length=20), nullable=False),
    sa.Column('major', sa.String(length=20), nullable=False),
    sa.Column('t_lass', sa.String(length=20), nullable=False),
    sa.Column('course', sa.String(length=10), nullable=False),
    sa.Column('score', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('stu_card'),
    sa.UniqueConstraint('stu_card')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('rdatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('message')
    # ### end Alembic commands ###
